//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VBACodeAnalysis.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VBACodeAnalysis.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Close [#]filenumber に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CloseErrorMsg {
            get {
                return ResourceManager.GetString("CloseErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input [#]filenumber, varname [, varname]... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputErrorMsg {
            get {
                return ResourceManager.GetString("InputErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line Input [#]filenumber, varname に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LineInputErrorMsg {
            get {
                return ResourceManager.GetString("LineInputErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open path For {Append, Binary, Output, Random} [Access {Read, Write, Read Write}][Read, Write, Read Write] As [#]filenumber に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenErrorMsg {
            get {
                return ResourceManager.GetString("OpenErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print [#]filenumber, var [, or ; var]... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PrintErrorMsg {
            get {
                return ResourceManager.GetString("PrintErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write [#]filenumber, var [, or ; var]... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WriteErrorMsg {
            get {
                return ResourceManager.GetString("WriteErrorMsg", resourceCulture);
            }
        }
    }
}
